"""mealplans table

Revision ID: 2c7cdd252799
Revises: 87bb14f18be0
Create Date: 2024-03-18 23:14:54.019344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7cdd252799'
down_revision = '87bb14f18be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_user_id'))

    op.drop_table('meal_plan')
    # ### end Alembic commands ###
