"""meals table

Revision ID: 992e8375953c
Revises: 2c7cdd252799
Create Date: 2024-03-22 02:15:45.737346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992e8375953c'
down_revision = '2c7cdd252799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_meal_plan_id'), ['meal_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_meal_plan_id'))

    op.drop_table('meal')
    # ### end Alembic commands ###
