"""foodintakes table

Revision ID: d9d334bfb5b0
Revises: 6156fe395c73
Create Date: 2024-03-22 02:38:42.287958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d334bfb5b0'
down_revision = '6156fe395c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_intake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_intake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_intake_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_intake_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_intake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_intake_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_intake_food_item_id'))

    op.drop_table('food_intake')
    # ### end Alembic commands ###
